- roles/bootnode/tasks/main.yml
test-templates repository was renamed to [deployment-azure](https://github.com/oraclesorg/deployment-azure) and `TestTestNet` subfolder to `nodes`, so existing links must be updated.
> Update links after test-templates repo was renamed

- group_vars/all.example
> Fix binary url

- group_vars/all.network
- roles/oracles-netstats/templates/app.json.j2
- roles/oracles-parity/templates/app.json.j2
- site.yml
In case custom SSL certificates are installed, it would be simpler to provide full link to public address of the netstats server (https://....) with correct protocol and without port number.
> Let NETSTATS_SERVER contain full link

- roles/nginx/templates/default.conf.j2
Comment out adding Access-Control-Allow- headers in nginx as they are set by parity on bootnodes.
> Comment out adding Access-Control-Allow- headers

- group_vars/all.example
Added line to group_vars/all.example to force remote node to use python3 instead of python2.7
reason being: fresh install of ubuntu 16.04 does not have python2.7 by default and it eases deployment process on cloud services other than AWS
> (Fix) Add python3 support for remote node core branch

- group_vars/all.example
Added line to group_vars/all.example to force remote node to use python3 instead of python2.7
reason being: fresh install of ubuntu 16.04 does not have python2.7 by default and it eases deployment process on cloud services other than AWS
> (Fix) Add python3 support for remote node sokol branch

- group_vars/all.example
Added line to group_vars/all.example to force remote node to use python3 instead of python2.7
reason being: fresh install of ubuntu 16.04 does not have python2.7 by default and it eases deployment process on cloud services other than AWS
> (Fix) Add python3 support for remote node master branch

- group_vars/all.example
- group_vars/all.network
Previous merge was into wrong config file
> (Fix) moved ansible_python_interpreter from all.example to all.network

- group_vars/all.example
- group_vars/all.network
- roles/bootnode/templates/node.toml.j2
- roles/moc/templates/node.toml.j2
- roles/poa-parity/templates/poa-parity.j2
- roles/validator/templates/node.toml.j2
Add options `bootnode_archive`, `moc_archive`, `validator_archive` with possible values `"on"`/`"off"` to corresponding roles to create a node that keeps record of all txs.
This closes #42
> Options to create archive-nodes

- roles/bootnode/templates/node.toml.j2
- roles/moc/templates/node.toml.j2
- roles/validator/templates/node.toml.j2
Add `tracing = "on"` parameter in node.toml files for node in archiving mode.
> Core: Add tracing for archiving nodes

- roles/bootnode/templates/node.toml.j2
- roles/moc/templates/node.toml.j2
- roles/validator/templates/node.toml.j2
Add `tracing = "on"` parameter in node.toml files for archiving nodes.
> Sokol: Add tracing for archiving nodes

- group_vars/all.example
- group_vars/all.network
* **Not so important**: in master branch `group_vars/all.example` and `group_vars/all.network` files contain different default values for region and ami in comparison with `core` and `sokol` branches
* **More important**: update current ami version. When this will later be merged into `core` and `sokol`, ami will be updated to the latest version (2018-02-05) for `us-east-1, 16.04 LTS, amd64, hvm:ebs-ssd` (see https://cloud-images.ubuntu.com/locator/ec2/ )
> Update AWS ami

- group_vars/all.example
Almost all nodes are updated to `1.9.2` on sokol now.
Change default value in playbook to `1.9.2` as well so that newly-created nodes would run it.
> Sokol: Update default parity version to 1.9.2

- group_vars/all.network
In https://github.com/poanetwork/deployment-playbooks/pull/70 also should have updated version and checksum in `all.network` file
> Sokol: Update parity version to 1.9.2 in all.network

- roles/bootnode/templates/node.toml.j2
Some parameters were renamed in parity 1.9.2:
* `threads` -> `processing_threads`
* `min_peers`, `max_peers` (only for archiving bootnodes) - not sure how it worked in the first place, because they were placed in `[footprint]` section. They are not needed actually, so remove them.
> Sokol: upd bootnode params to fit 1.9.2 (part I)

- roles/bootnode/templates/node.toml.j2
In parity 1.9.2 parity's jsonrpc by default assumes all `Host`s to be blacklisted, in contrast with previous version where they were whitelisted by default. So now without setting `cors` option on bootnodes corresponding to rpc endpoint, sites like MyEtherWallet can't connect to the network.
I separate this PR from [Part I](https://github.com/poanetwork/deployment-playbooks/pull/72), because this one will probably raise some discussion, so Part I can be merged independently.
For future, I propose we separate existing role "bootnode" into two:
* "bootnode" bootnode - accessible only for peer discovery, without nginx and cors. Maybe a cluster of them can use orchestrator
* "rpc" node - the one users can connect to to use rpc
these two types might require different settings and resources
> Sokol: upd bootnode params to fit 1.9.2 (part II)

- group_vars/all.example
- group_vars/all.network
- roles/bootnode/templates/node.toml.j2
Related to https://github.com/poanetwork/deployment-playbooks/issues/85
Updates from _sokol_:
* Parity version and checksums (https://github.com/poanetwork/deployment-playbooks/pull/70, https://github.com/poanetwork/deployment-playbooks/pull/71)
* Bootnode config (https://github.com/poanetwork/deployment-playbooks/pull/72, https://github.com/poanetwork/deployment-playbooks/pull/73)
> Core: updates for parity 1.9.2

- .gitignore
- Makefile
- Vagrantfile
- tests/bootnode.sh
- tests/explorer.sh
- tests/moc.sh
- tests/netstat.sh
- tests/validator.sh
This PR adds code for local testing of the playbooks.
It uses Vagrant and VirtualBox for running virtual machines. In this virtual machines vagrant runs ansible playbooks and integration tests after completion.
`poa_platform` enviornmental variable select the platform to run tests on - `ubuntu` or `centos`.
`Makefile` automates one-by-one test of all the playbooks types. It takes about 20 minutes on i5 to pass full set of tests.
One may want to run provisioning for only one machine: `vagrant up explorer`.
> Local deployment environment

- group_vars/all.example
- group_vars/all.network
Remove variables `snmp_syslocation`, `snmp_ipsubnet`, `nameservers`, `ntpservers` as they are not used currently. These settings are usually provided by the hosting platform.
Closes #88 #56
> Remove unused variables related to dns and ntp servers

- roles/bootnode/templates/node.toml.j2
Before, trying to open rpc port via GET (e.g. http://192.0.2.1:8545) would redirect to localhost. In 1.10 this is no longer the case, instead a page with 404 error is returned
Just to be safe, I propose we explicitly disable ui and dapps in config
> (Upd 1.10) Explicitly disable ui and dapps for bootnodes

- roles/bootnode/templates/node.toml.j2
This PR partially reverts the previous one (https://github.com/poanetwork/deployment-playbooks/pull/105) as it turns out that `/api/health` is a "built-in" dapp
We can get info on sync status, number of peers from jsonrpc, but not on time drift. Since we don't have any actual dapps stored in parity, I think we can keep this option enabled
> (SOKOL UPD 1.10) Revert explicitly disabling dapps on bootnodes

- roles/explorer/templates/poa-chain-explorer.j2
- roles/netstat/templates/poa-dashboard.j2
- roles/poa-netstats/templates/poa-netstats.j2
- roles/poa-parity/templates/poa-chain-explorer.j2
- roles/poa-parity/templates/poa-dashboard.j2
- roles/poa-parity/templates/poa-netstats.j2
- roles/poa-parity/templates/poa-pm2.j2
- roles/poa-pm2/templates/poa-pm2.j2
Looks like there was a typo in template unnecesarry env variable. Doesn't affect anything actually, but I beleive should be cleaned up. 
#112 Is the corresponding issue
> Remove unnecesary envvar declaration

- bootnode.yml
- explorer.yml
- group_vars/all.example
- group_vars/all.network
- moc.yml
- netstat.yml
- roles/bootnode-access/tasks/ec2.yml
- roles/explorer-access/tasks/ec2.yml
- roles/moc-access/tasks/ec2.yml
- roles/netstat-access/tasks/ec2.yml
- roles/validator-access/tasks/ec2.yml
- validator.yml
This is a cherry-picked commit from master, that is useful in production branches
It changes naming of aws security groups and prevents them from being overwritten if they already exist.
It closes an old issue #43
> (Sokol) update security group namings

- roles/nginx/templates/default.conf.j2
Set max allowed request body size to `128k` (same as infura) to prevent huge requests from overloading nodes (default value is `1M`).
> (Sokol) Limit request bodysize in nginx

- roles/nginx/templates/default.conf.j2
Set max allowed request body size to `128k` (same as infura) to prevent huge requests from overloading nodes (default value is `1M`).
Cousine of https://github.com/poanetwork/deployment-playbooks/pull/148
> (Core) Limit request bodysize in nginx

- roles/bootnode/templates/node.toml.j2
- roles/validator/templates/node.toml.j2
Refactor and set values of `max_peers = 100` (for bootnodes and validators) and of `snapshot_peers = 25` (only for bootnodes).
This should improve peers discovery.
Cousin of #150
> (Sokol) set max peers and snaphost peers options

- roles/bootnode/templates/node.toml.j2
- roles/validator/templates/node.toml.j2
Refactor and set values of `max_peers = 100` (for bootnodes and validators) and of `snapshot_peers = 25` (only for bootnodes).
This should improve peers discovery.
> (Core) set max peers and snaphost peers options

- roles/bootnode/templates/node.toml.j2
- roles/nginx/templates/default.conf.j2
- roles/validator/templates/node.toml.j2
Set values for 
* `max_peers` (bootnode & validator)
* `snapshot_peers` (bootnode)
* `client_max_body_size` (nginx)
These are latest updates from sokol and core branches (see https://github.com/poanetwork/deployment-playbooks/pull/151, https://github.com/poanetwork/deployment-playbooks/pull/148)
> Merge latest changes from prod branches

- aws/explorer.yml
- aws/moc.yml
- aws/netstat.yml
- aws/validator.yml
AWS instance names were using `bootnode_instance_name`
> Fix instance names

- group_vars/all.example
- group_vars/all.network
Update default parity version in playbooks
Cousin of https://github.com/poanetwork/deployment-playbooks/pull/158
> (CORE) Update default parity version to 1.11.8

- aws/bootnode.yml
- aws/explorer.yml
- aws/moc.yml
- aws/netstat.yml
- aws/roles/bootnode-access/tasks/ec2.yml
- aws/roles/explorer-access/tasks/ec2.yml
- aws/roles/moc-access/tasks/ec2.yml
- aws/roles/netstat-access/tasks/ec2.yml
- aws/roles/validator-access/tasks/ec2.yml
- aws/validator.yml
I've found and tested that if we replace `vpc_id` and `vpc_subnet_id` with empty value Ansible uses the appropriate defaults.
> Fix defaults in EC2 creation (176 issue)

- roles/nodejs/defaults/main.yml
- roles/nodejs/tasks/ubuntu.yml
As described at #189, playbooks were broken due to the fact that GPG key, which is used during process of nodejs installation are not valid anymore. This change will allow us to get rid of GPG keys and use link to nodejs repo instead. Also simplifies configuration
> Change the way nodejs installed (xDAI)

- roles/nodejs/defaults/main.yml
- roles/nodejs/tasks/ubuntu.yml
As described at #189, playbooks were broken due to the fact that GPG key, which is used during process of nodejs installation are not valid anymore. This change will allow us to get rid of GPG keys and use link to nodejs repo instead. Also simplifies configuration.
> Change the way nodejs installed (Master)

- .circleci/config.yml
- aws/bootnode.yml
- aws/explorer.yml
- aws/moc.yml
- aws/netstat.yml
- aws/roles/bootnode-access/tasks/ec2.yml
- aws/roles/explorer-access/tasks/ec2.yml
- aws/roles/moc-access/tasks/ec2.yml
- aws/roles/netstat-access/tasks/ec2.yml
- aws/roles/validator-access/tasks/ec2.yml
- aws/validator.yml
- roles/moc/templates/node.toml.j2
- roles/validator/templates/node.toml.j2
As shown in #174 `max_peers` and `min_peers` variables are set in the wrong (`footprint`) section. The purpose of this PR is to migrate those variables to `network` section at `master` branch.
Related PRs are #186 and #187
> Fix `max_peers` and `min_peers` section in node.toml (Master)

- group_vars/all.example
- group_vars/all.network
Update default parity version to `2.2.1`
> (SOKOL) Update default parity version to 2.2.5

- bootnode.yml
- explorer.yml
- moc.yml
- netstat.yml
- roles/bootnode-access/tasks/ec2.yml
- roles/explorer-access/tasks/ec2.yml
- roles/moc-access/tasks/ec2.yml
- roles/moc/templates/node.toml.j2
- roles/netstat-access/tasks/ec2.yml
- roles/validator-access/tasks/ec2.yml
- roles/validator/templates/node.toml.j2
- validator.yml
As shown in #174 `max_peers` and `min_peers` variables are set in the wrong (`footprint`) section. The purpose of this PR is to migrate those variables to `network` section at `core` branch.
Related PRs - #185 and #187
> Fix `max_peers` and `min_peers` section in node.toml (Core) 

- bootnode.yml
- explorer.yml
- moc.yml
- netstat.yml
- roles/bootnode-access/tasks/ec2.yml
- roles/explorer-access/tasks/ec2.yml
- roles/moc-access/tasks/ec2.yml
- roles/moc/templates/node.toml.j2
- roles/netstat-access/tasks/ec2.yml
- roles/validator-access/tasks/ec2.yml
- roles/validator/templates/node.toml.j2
- validator.yml
As shown in #174 `max_peers` and `min_peers` variables are set in the wrong (`footprint`) section. The purpose of this PR is to migrate those variables to `network` section at `sokol` branch.
Related PRs are #185 and #186
> Fix `max_peers` and `min_peers` section in node.toml (Sokol)

- roles/bootnode/tasks/main.yml
- roles/bootnode/templates/node.toml.j2
- roles/explorer/tasks/main.yml
- roles/explorer/templates/node.toml.j2
- roles/moc/tasks/main.yml
- roles/moc/templates/node.toml.j2
- roles/nginx/tasks/main.yml
- roles/preconf/tasks/ssh.yml
- roles/validator/tasks/main.yml
- roles/validator/templates/node.toml.j2
Fixes #175
Fixes #194, but still not making playbooks fully compatible with Ubuntu 18.
Also modifies the way Python and python-pip is used. (related to #195, but not fixes it). I have decided to remove hardcoded values and replace it with variables that has defaults.
> Fix SSH ciphers used by SSHD and replace private IP with public at node.toml

- group_vars/centos
- group_vars/ubuntu
Update default parity version used in `master` branch to 2.2.5
Closes #201
> Phahulin patch 2

- group_vars/all.network
Change default parity version to 2.3.2 on core
> (Core) Update default parity to 2.3.2

- roles/poa-netstats/defaults/main.yml
Purpose of this PR is to update default API version from old (9773b5b) to the new one.
> Update netstat api version

- roles/poa-netstats/defaults/main.yml
Replace hard-coded (and outdated) commit number of netstats version with `master`.
> Use the latest version of netstats agent

- roles/nginx/tasks/main.yml
- roles/preconf/tasks/ssh.yml
Based on https://github.com/poanetwork/deployment-playbooks/pull/208
1. use pip version based on available `python` version
2. use different list of ssh ciphers, which is supported on both `Ubuntu 16.04` and `Ubuntu 18.04`
> Fix ciphers and pip version to support Ubuntu 18.04

- roles/preconf/tasks/ssh.yml
Apply SSH cipher fix for Ubuntu 18.04 (as in https://github.com/poanetwork/deployment-playbooks/pull/229/)
> (Sokol) Fix ciphers for Ubuntu 18.04

- roles/preconf/tasks/ssh.yml
Apply SSH cipher fix for Ubuntu 18.04 (as in https://github.com/poanetwork/deployment-playbooks/pull/229/)
> (Core) Fix ciphers for Ubuntu 18.04

- group_vars/ubuntu
Should be merged with https://github.com/poanetwork/poa-chain-spec/pull/122 because changes there are incompatible with previous versions of parity and at the same time new version is incompatible with old spec
> (Kovan) Update default parity version to 2.6.4

- group_vars/all.network
Should be merged with https://github.com/poanetwork/poa-chain-spec/pull/125 due to incompatibility with older parity version
> (Sokol) Update parity version to 2.6.4

- group_vars/all.network
Current spec.json is incompatible with this new version, so this PR should be merged together with https://github.com/poanetwork/poa-chain-spec/pull/128
> (Sokol) Update default parity version to 2.6.5

- aws/blockscout.yml
- aws/bootnode.yml
- aws/explorer.yml
- aws/group_vars/all.yml.example
- aws/moc.yml
- aws/netstat.yml
- aws/validator.yml
1. Remove idempotent  `id` to prevent errors when creating multiple instances.
2. Fix missing `allow_*` variables for security groups
> Fix aws playbooks

- group_vars/all.network
Sets default parity version to 2.6.5 compatible with Istanbul HF. Needs to be merged with https://github.com/poanetwork/poa-chain-spec/pull/131
> (Core) Update default parity version to 2.6.5

- group_vars/centos
- group_vars/ubuntu
Version update is required for Istanbul HF. This PR should be merged together with https://github.com/poanetwork/poa-chain-spec/pull/130
> (xDai) Update default parity version to 2.6.5
