poanetwork/deployment-playbooks

.gitignore, files/ssh_bootnode.pub, group_vars/all, group_vars/bootnode.example, group_vars/explorer.example, group_vars/mining.example, group_vars/netstat.example, group_vars/owner.example, roles/nodejs/tasks/main.yml, roles/oracles-parity/tasks/main.yml, roles/oracles-parity/templates/oracles-parity.j2
* remove `files/*.pub`
* create `group_vars/*.example` files separated by roles
* rename `parity_nouncles` variable to `PARITY_BIN_LOC`. Change filename from `parity-nouncles` to just `parity`
* add `NODE_SOURCE_DEB` variable with a link to node.js version to use.`
=> Small refactoring

roles/bootnode/tasks/main.yml, roles/explorer/tasks/main.yml, roles/moc/tasks/main.yml, roles/validator/tasks/main.yml
Move `bootnodes.txt` to `poa-chain-spec`
=> Replace bootnodes.txt location

bootnode.yml, group_vars/all.example, group_vars/all.network, validator.yml
Merge elastic ip option from master
=> Sokol: Merge elastic ip option from master

bootnode.yml, group_vars/all.example, group_vars/all.network, validator.yml
Merge option to set elastic ip
=> Core: Merge option to set elastic ip

group_vars/all.example, group_vars/all.network
=> Core: Rename repo

group_vars/all.example, group_vars/all.network
=> Sokol: Rename repo

group_vars/all.example
=> Add warning in all.example

group_vars/all.example, roles/nginx/templates/default.conf.j2, site.yml
Merge latest changes from master
=> Core: Merge latest changes from master

group_vars/all.example, roles/nginx/templates/default.conf.j2, site.yml
Merge latest changes from master
=> Sokol: Merge latest changes from master

roles/moc/templates/node.toml.j2, roles/validator/templates/node.toml.j2
Add `min_gas_price` to `[mining]` section of node.toml
=> Core: set min_gas_price to 1 gwei for validator and moc

roles/moc/templates/node.toml.j2, roles/validator/templates/node.toml.j2
Add `min_gas_price` to `[mining]` section of node.toml
=> Sokol: set min_gas_price to 1 gwei for validator and moc

roles/bootnode/defaults/main.yml, roles/explorer/defaults/main.yml, roles/moc/defaults/main.yml, roles/netstat/defaults/main.yml, site.yml
=> Role-level variables

group_vars/all.example, group_vars/all.network
Update binary url and sha256 checksum
=> (SOKOL UPD1.10) Update defaults for parity 1.10

group_vars/all.example, group_vars/all.network
Update default parity version to v1.10.6
=> (CORE) Update default parity version to 1.10.6

roles/poa-parity/defaults/main.yml
Update defaults of poa-parity role to use 1.10.6
=> Update default version of parity

.circleci/config.yml
=> Update ENV variables for CI

aws/bootnode.yml, aws/explorer.yml, aws/group_vars/all.yml.example, aws/moc.yml, aws/netstat.yml, aws/roles/bootnode-access/tasks/ec2.yml, aws/roles/explorer-access/tasks/ec2.yml, aws/roles/moc-access/tasks/ec2.yml, aws/roles/netstat-access/tasks/ec2.yml, aws/roles/validator-access/tasks/ec2.yml, aws/validator.yml
=> Fix for #143

aws/bootnode.yml, aws/explorer.yml, aws/moc.yml, aws/netstat.yml, aws/roles/bootnode-access/tasks/ec2.yml, aws/roles/explorer-access/tasks/ec2.yml, aws/roles/moc-access/tasks/ec2.yml, aws/roles/netstat-access/tasks/ec2.yml, aws/roles/validator-access/tasks/ec2.yml, aws/validator.yml
This one fixes #177 issue for Master branch.
=> Fix 177 issue (Master)

.circleci/config.yml
This PR fixes CI workflow similar to https://github.com/poanetwork/deployment-terraform/pull/64
=> Update circleci config according to deployment-terraform changes

bootnode.yml, explorer.yml, moc.yml, netstat.yml, roles/bootnode-access/tasks/ec2.yml, roles/explorer-access/tasks/ec2.yml, roles/moc-access/tasks/ec2.yml, roles/netstat-access/tasks/ec2.yml, roles/validator-access/tasks/ec2.yml, validator.yml
This one fixes #177 issue for Core branch.
=> Fix 177 issue (Core)

bootnode.yml, explorer.yml, moc.yml, netstat.yml, roles/bootnode-access/tasks/ec2.yml, roles/explorer-access/tasks/ec2.yml, roles/moc-access/tasks/ec2.yml, roles/netstat-access/tasks/ec2.yml, roles/validator-access/tasks/ec2.yml, validator.yml
This one fixes #177 issue for Sokol branch.
=> Fix 177 issue (Sokol)

blockscout.yml, group_vars/all.example, group_vars/all.network, group_vars/blockscout.example, hosts.example, roles/blockscout-access/tasks/ec2.yml, roles/blockscout-access/tasks/main.yml, roles/blockscout-access/tasks/ufw.yml, roles/blockscout/handlers/main.yml, roles/blockscout/tasks/main.yml, roles/blockscout/templates/dev.secret.j2, roles/blockscout/templates/node.toml.j2, roles/blockscout/templates/poa-blockscout.j2, roles/elixir/defaults/main.yml, roles/elixir/tasks/main.yml, site.yml
Add BlockScout and Elixir roles
=> BlockScout role (Core)

group_vars/centos, group_vars/ubuntu
Fixed links to parity binaries
=> Update parity links

group_vars/ubuntu
Change default parity version to 2.3.2
=> Update default parity version

.gitignore, aws/blockscout.yml, aws/bootnode.yml, aws/explorer.yml, aws/moc.yml, aws/netstat.yml, aws/roles/blockscout-access/tasks/ec2.yml, aws/roles/blockscout-access/tasks/main.yml, aws/roles/bootnode-access/tasks/ec2.yml, aws/roles/bootnode-access/tasks/main.yml, aws/roles/explorer-access/tasks/ec2.yml, aws/roles/explorer-access/tasks/main.yml, aws/roles/moc-access/tasks/ec2.yml, aws/roles/moc-access/tasks/main.yml, aws/roles/netstat-access/tasks/ec2.yml, aws/roles/netstat-access/tasks/main.yml, aws/roles/validator-access/tasks/ec2.yml, aws/roles/validator-access/tasks/main.yml, aws/validator.yml
Fix #228 bug
Due to incorrect host name set no security group rules was created along with EC2 instance.
=> Fix the bug with security group rules creation

roles/moc/defaults/main.yml, roles/validator/defaults/main.yml
We forgot to change the limit in playbooks.
=> (xDai) Increase block gas limit to 10M

roles/moc/defaults/main.yml, roles/validator/defaults/main.yml
We forgot to change the limit in playbooks.
=> (Kovan) Increase block gas limit to 10M
